spring.application.name=task-manager-secure
server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/task_manager}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:task_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:task_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.jwt.secret=${APP_JWT_SECRET:VGhpc0lzQVNlY3VyZUJhc2U2NEp3dFNlY3JldEtleUZvclByb2plY3QxMjM0NTY=}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:86400000}
app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost:4201,http://localhost:4200}
app.seed.enabled=${APP_SEED_ENABLED:false}
